### ISSUE TITLE
Render Function

### ISSUE THREAD

**Issue by abbasmashaddy72** [rawilk/laravel-breadcrumbs#1]
### Laravel Breadcrumbs Version

v3.0.1

### Laravel Version

v9.19

### Bug description

I am unable to use
Normal Render `{{ Breadcrumbs::render('#') }}`
It shows the text

I have to change the syntax to `{!! Breadcrumbs::render('#') !!}`
to get the UI output

### Steps to reproduce

Followed the Documentation

**Comment by rawilk** [comment]
Not really an issue with the package itself, just typos in the docs. The docs reflect the correct way to render them using `{!!` instead of `{{` to prevent blade from escaping html characters.

You're free to use it that way, but an easier way to render the breadcrumbs is by using the blade component:

```php
<x-breadcrumbs breadcrumbs="#" />
```

See: https://randallwilk.dev/docs/laravel-breadcrumbs/v3/usage/outputting-breadcrumbs#user-content-blade-component

**Comment by abbasmashaddy72** [comment]
Okay Thanks
